word_list = [
    'Superman',
    'Batman',
    'Spider-Man',
    'Wonder-Woman',
    'Iron Man',
    'Captain-America',
    'Hulk',
    'Thor',
    'Black Widow',
    'Flash',
    'Green Lantern',
    'Aquaman',
    'Wolverine',
    'Black-Panther',
    'Doctor-Strange',
    'Captain-Marvel',
    'Ant-Man',
    'Deadpool',
    'Green-Arrow',
    'The-Flash', 
]